services:
  # Contenedor backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backendPinturillo
    ports: 
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: unless-stopped
  # Contenedor frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontendPinturillo
    env_file:
      - ./.env 
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped